[input]
html_selector = "main"
base_directory = "/Users/caesar/repos/caesarb-34/caesarb-34.github.io/docs"

[[input.files]]
path = "pages/about-me.html"
url = "/pages/about-me.html"
title = "About Me"

[[input.files]]
path = "pages/blog.html"
url = "/pages/blog.html"
title = "Blog"
